### ISSUE TITLE
Curious

### ISSUE THREAD

**Issue by Shadowfita** [PrivateServerEmulator/ME3PSE#2]
Hi!

I was just wondering what _is not_ currently working in this project or needs to be completed?

Thanks!

**Comment by Erik-JS** [comment]
**What features are not available yet?**
> Quick match filters: after client request, PSE returns lobbies according to these rules: 1- creation time, 2- is active, 3- has free slot. Any other rules are currently ignored (number of required/unused DLC's, private/public lobby, random or specific map/difficulty/enemy);
> Host migration: currently under research.

**When will feature X be implemented? / When is the next release of PSE?**
> When it's done.

https://me3tweaks.com/forums/viewtopic.php?f=10&t=9#p33

**Comment by Shadowfita** [comment]
Sorry about that!

Thanks!
