### ISSUE TITLE
License terms?

### ISSUE THREAD

**Issue by frabert** [PrivateServerEmulator/ME3PSE#7]
Hi! What license is the source code of ME3PSE released under? Can I create a fork and redistribute it? Can I create a derivative server based on your work, and if so, what are the attribution requirements?

Thanks, and great job on this tool!

**Comment by Erik-JS** [comment]
That's a good question, lol!

Well, I can't stop people from copying what they want, but I'll only ask anyone reading this to have the minimum decency of giving credit where credit is due.

All repositories directly under my account use MIT license. PSE isn't exactly "mine", but I'm maintaining it now, so in absence of anything else you can consider PSE being under MIT as well - in other words, just give credits to Warranty Voider, me and the people in "special thanks". I'll add a proper license file to this repository in the future.
